### ISSUE TITLE
loading saved supreme court corpus causes an error

### ISSUE THREAD

**Issue by idc9** [chartbeat-labs/textacy#136] opened 2017-10-23 21:07 UTC
Loading the Supreme Court data set after turning it into a textacy Corpus causes an error. 

## Current Behavior

Download data set, create textacy corpus, save corpus, then try to load saved version of the corpus. Warning: the below code takes about an hour.
```
import textacy
from textacy.datasets.supreme_court import SupremeCourt

data_dir = 'XXX'

sc = SupremeCourt(data_dir)
sc.download()

text_stream, metadata_stream = textacy.fileio.split_record_fields(sc.records(), 'text')
c = textacy.Corpus('en', texts=text_stream, metadatas=metadata_stream)

# save corpus
c.save(data_dir, name='scotus', compression='gzip')

# try to load saved corpus
# this line breaks
corpus = textacy.Corpus.load(data_dir, name='scotus', compression='gzip')
```
Causes the  following error
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-f8c95a5b7a1a> in <module>()
----> 1 corpus = textacy.Corpus.load(data_dir, name='scotus', compression='gzip')

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/textacy/corpus.py in load(cls, path, name, compression)
    279         metadata_stream = fileio.read_json_lines(meta_fname, mode=meta_mode)
    280         spacy_docs = fileio.read_spacy_docs(corpus.spacy_vocab, docs_fname)
--> 281         for spacy_doc, metadata in zip_(spacy_docs, metadata_stream):
    282             corpus.add_doc(
    283                 Doc(spacy_doc, lang=corpus.spacy_lang, metadata=metadata))

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/textacy/fileio/read.py in read_spacy_docs(spacy_vocab, filepath)
    171     with open_sesame(filepath, mode='rb') as f:
    172         for bytes_string in SpacyDoc.read_bytes(f):
--> 173             yield SpacyDoc(spacy_vocab).from_bytes(bytes_string)
    174 
    175 

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.from_bytes (spacy/tokens/doc.cpp:12361)()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/spacy/serialize/packer.pyx in spacy.serialize.packer.Packer.unpack_into (spacy/serialize/packer.cpp:6258)()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/spacy/serialize/packer.pyx in spacy.serialize.packer.Packer._char_decode (spacy/serialize/packer.cpp:7791)()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/spacy/tokens/doc.pyx in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:10095)()

AssertionError:
```

If I limit the above code to say 100 files the above code works fine (i.e. 
```
text_stream, metadata_stream = textacy.fileio.split_record_fields(sc.records(limit=100), 'text')
```
does **not** cause the above error.

## Your Environment
Note this error happens for both the version of textacy on pypi and the version of textacy on github as of today (10/23/17)

{'platform': 'darwin',
 'python': '3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]',
 'spacy': '1.9.0',
 'spacy_models': ['en'],
 'textacy': '0.4.1'}

**Comment by bdewilde** [comment] 2017-10-26 21:22
Hi @idc9 , It looks like the problem is in `spacy`'s built-in serialization `Packer`, which has been known to have issues, and which has been removed entirely from v2.0. I look forward to dropping `textacy`'s dependence on it ASAP. In the meantime, though... I'm not sure we have any good options, but I can try to debug. Was there a message below that `AssertionError`?

**Comment by idc9** [comment] 2017-10-27 00:07
Nope, there nothing below `AssertionError`. If you can debug this it would be great, but it might be \ challenging. The error does not happen when I limit the records to smaller corpuses i.e. you have to run the whole thing (~ 1 hr) to reproduce it. I also tried loading cases year by year (to attempt to identify which case is causing a problem), but this also did not cause the error.

**Comment by idc9** [comment] 2017-12-09 17:43
I updated spacy/textacy and there is now a different error with the supreme court data set (this time when creating the textacy corpus).
 
Running this code
```python
import textacy
from textacy.datasets.supreme_court import SupremeCourt

data_dir = 'XXX'

sc = SupremeCourt(data_dir)
text_stream, metadata_stream = textacy.fileio.split_record_fields(sc.records(), 'text')
corpus = textacy.Corpus('en', texts=text_stream, metadatas=metadata_stream)
```

gives the follow error message
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-3-89ca5159e748> in <module>()
      2 
      3 text_stream, metadata_stream = textacy.fileio.split_record_fields(sc.records(), 'text')
----> 4 corpus = textacy.Corpus('en', texts=text_stream, metadatas=metadata_stream)
      5 
      6 corpus.save(data_dir + 'textacy_scotus')

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/textacy/corpus.py in __init__(self, lang, texts, docs, metadatas)
    149             raise ValueError(msg)
    150         if texts:
--> 151             self.add_texts(texts, metadatas=metadatas)
    152         elif docs:
    153             if metadatas:

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/textacy/corpus.py in add_texts(self, texts, metadatas, n_threads, batch_size)
    280             texts, n_threads=n_threads, batch_size=batch_size)
    281         if metadatas:
--> 282             for spacy_doc, metadata in compat.zip_(spacy_docs, metadatas):
    283                 self._add_textacy_doc(
    284                     Doc(spacy_doc, lang=self.spacy_lang, metadata=metadata))

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/spacy/language.py in pipe(self, texts, as_tuples, n_threads, batch_size, disable, cleanup)
    553         original_strings_data = None
    554         nr_seen = 0
--> 555         for doc in docs:
    556             yield doc
    557             if cleanup:

nn_parser.pyx in pipe()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/cytoolz/itertoolz.pyx in cytoolz.itertoolz.partition_all.__next__ (cytoolz/itertoolz.c:14538)()

nn_parser.pyx in pipe()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/cytoolz/itertoolz.pyx in cytoolz.itertoolz.partition_all.__next__ (cytoolz/itertoolz.c:14538)()

pipeline.pyx in pipe()

pipeline.pyx in spacy.pipeline.Tagger.predict()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/api.py in predict(self, X)
     53     def predict(self, X):
     54         for layer in self._layers:
---> 55             X = layer(X)
     56         return X
     57 

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/api.py in predict(seqs_in)
    291     def predict(seqs_in):
    292         lengths = layer.ops.asarray([len(seq) for seq in seqs_in])
--> 293         X = layer(layer.ops.flatten(seqs_in, pad=pad))
    294         return layer.ops.unflatten(X, lengths, pad=pad)
    295 

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/api.py in predict(self, X)
     53     def predict(self, X):
     54         for layer in self._layers:
---> 55             X = layer(X)
     56         return X
     57 

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/resnet.py in __call__(self, X)
     13 
     14     def __call__(self, X):
---> 15         return X + self._layers[0](X)
     16 
     17     def begin_update(self, X, drop=0.):

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/api.py in predict(self, X)
     53     def predict(self, X):
     54         for layer in self._layers:
---> 55             X = layer(X)
     56         return X
     57 

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/model.py in __call__(self, x)
    159             Must match expected shape
    160         '''
--> 161         return self.predict(x)
    162 
    163     def pipe(self, stream, batch_size=128):

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/thinc/neural/_classes/convolution.py in predict(self, X)
     23 
     24     def predict(self, X):
---> 25         return self.ops.seq2col(X, self.nW)
     26 
     27     def begin_update(self, X__bi, drop=0.0):

ops.pyx in thinc.neural.ops.NumpyOps.seq2col()

/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/cymem/cymem.pyx in cymem.cymem.Pool.alloc (cymem/cymem.cpp:1091)()

MemoryError: Error assigning 18446744071574252160 bytesError assigning 18446744071574252160 bytesError assigning 18446744071574252160 bytesError assigning 18446744071574252160 bytes
```


---

```
{'platform': 'darwin',
 'python': '3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]',
 'spacy': '2.0.5',
 'spacy_models': ['en'],
 'textacy': '0.5.0'}
```

**Comment by bdewilde** [comment] 2017-12-09 17:51
😖 

Looks like this error is happening deep in the bowels of spacy, and you'll be better served reporting it [there](https://github.com/explosion/spaCy/issues). I recommend trying this in a way that bypasses textacy in the vicinity of the error: use textacy to stream the texts, sure, but pass them directly into `spacy.<language>.pipe()`. See if there's anything weird about the text(s) that raises the exception. Sorry I'm not more help with this...

**Comment by bdewilde** [comment] 2018-04-24 00:34
Hi @idc9 , I'm going to close this issue out, since it's effectively a duplicate of #183 , and progress has been there rather than here.

**Closed by bdewilde** 2018-04-24 00:34 UTC
