### ISSUE TITLE
Better handling of corpus of 200k+ docs

### ISSUE THREAD

**Issue by brtknr** [chartbeat-labs/textacy#183] opened 2018-03-26 08:50 UTC
I have a corpus of 200k+ docs (45 words per doc, std=26) and it takes around 20 mins to load and process the data into a textacy corpus. Trying to save the processed object to disk throws pickling error... unsurprising considering this corpus utilises around 15GB of swap space on my SSD. It would be nice if there was an easier way to work with large corpuses.

## Expected Behavior
It should be easy to save and load large processed object to and from disk and it should also be able to see how many docs have been processed of the total input.

## Current Behavior
Takes a long time to process a large corpus.
Cannot save the processed object to disk because it is too big.
It is necessary to reprocess the entire corpus each time it is necessary to work with the corpus.
There is no indication of progress.

## Possible Solution
Fast read and write solution to and from disk using disk key-value storage libraries like hdfs?

Also include the following in the `add_text` function call loop:
```python
print('{} docs have been processed'.format(text_index), end='\r')
```

## Steps to Reproduce (for bugs)
Try creating a large corpus (200k+ docs with 30 words per doc) and saving it to disk.

## Context
I am trying to process description of incidents submitted during insurance claims... and takes a long time to load from disk.

## Your Environment

- **platform:** darwin
- **python:** 3.6.4 (default, Mar  1 2018, 18:36:50)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
- **spacy:** 2.0.8
- **spacy_models:** ['en_core_web_lg', 'en']
- **textacy:** 0.6.0

**Comment by idc9** [comment] 2018-04-06 16:28
I'm having similar problems with large corpuses. I can save the corpus to disk when I only process a few of the documents, but when I try to process the whole corpus saving becomes problematic. I'll post a separate issue when I figure out exactly what's going wrong.

## Current behavior

When I try to save the corpus I usually get `OSError: [Errno 22] Invalid argument`. This happens with pickle, gzip and bz2 (e.g. `corpus.save('blah')`, `corpus.save('blah.gz')`). 

For pickling, at least, I think the issue is related to [this stackoverflow post](https://stackoverflow.com/questions/31468117/python-3-can-pickle-handle-byte-objects-larger-than-4gb). It's not clear to me if this problem is supposed to have been fixed, but when I implement they hack they suggest (see below) I am able to pickle the corpus.

I am able to get the gzip to save on my university's cluster (linux). However, when I try to load the gzip'ed corpus on my laptop (mac) I get an error (will describe in a separate issue). 


## Possible temporary hack

I can pickle the corpus when I implement the suggested hack from the above stackoverflow post. Here is a python script based on this post which works for me.

``` python
import pickle
from cytoolz import itertoolz
from textacy import Corpus
from spacy.util import get_lang_class


def save_corpus(corpus, fname):
    # save the spacy_lang data as the first element
    to_save = [corpus.spacy_lang.meta]
    to_save.extend([doc.spacy_doc for doc in corpus])

    pickle_dump(to_save, fname)


def load_corpus(fname):
    loaded = pickle_load(fname)

    spacy_lang_meta = loaded[0]
    spacy_docs = loaded[1:]

    first_spacy_doc, spacy_docs = itertoolz.peek(spacy_docs)

    spacy_lang = get_lang_class(spacy_lang_meta['lang'])(vocab=first_spacy_doc.vocab,
                                                         meta=spacy_lang_meta)

    for name in spacy_lang_meta['pipeline']:
        spacy_lang.add_pipe(spacy_lang.create_pipe(name))

    corpus = Corpus(spacy_lang, docs=spacy_docs)
    return corpus


class MacOSFile(object):

    def __init__(self, f):
        self.f = f

    def __getattr__(self, item):
        return getattr(self.f, item)

    def read(self, n):
        # print("reading total_bytes=%s" % n, flush=True)
        if n >= (1 << 31):
            buffer = bytearray(n)
            idx = 0
            while idx < n:
                batch_size = min(n - idx, 1 << 31 - 1)
                # print("reading bytes [%s,%s)..." % (idx, idx + batch_size), end="", flush=True)
                buffer[idx:idx + batch_size] = self.f.read(batch_size)
                # print("done.", flush=True)
                idx += batch_size
            return buffer
        return self.f.read(n)

    def write(self, buffer):
        n = len(buffer)
        # print("writing total_bytes=%s..." % n, flush=True)
        idx = 0
        while idx < n:
            batch_size = min(n - idx, 1 << 31 - 1)
            # print("writing bytes [%s, %s)... " % (idx, idx + batch_size), end="", flush=True)
            self.f.write(buffer[idx:idx + batch_size])
            # print("done.", flush=True)
            idx += batch_size


def pickle_dump(obj, file_path):
    with open(file_path, "wb") as f:
        return pickle.dump(obj, MacOSFile(f), protocol=pickle.HIGHEST_PROTOCOL)


def pickle_load(file_path):
    with open(file_path, "rb") as f:
        return pickle.load(MacOSFile(f))
```





## Your Environment
- **platform:** darwin
- **python:** 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
- **spacy:** 2.0.5
- **spacy_models:** ['en']
- **textacy:** 0.6.0

**Comment by brtknr** [comment] 2018-04-07 00:35
How big is your corpus? How long does it take to read/write? Do you have a hdd or a ssd?

**Comment by bdewilde** [comment] 2018-04-09 02:16
Hi @brtknr and @idc9 , sorry about the problems you're having. There are a few independent issues, I'll take them one at a time.

Unfortunately, the underlying implementation for (de-)serializing data to/from bytes in spaCy v2.0+ is problematic, so in textacy v0.5 I fell back on pickle, which has its own problems (as you well know) but at least I could get working. I _think_ I may revisit that decision, since we really shouldn't need pickle when spaCy can readily read/write plain bytes. I'll probably have to re-ping the spaCy folks about this — I never got a response to my previous attempt.

I can't do much about the time required to parse so many texts, but I can help you track your progress. I've added a debug logging statement to the Corpus that reports every doc that gets added (note: 200k texts => 200k logging statements, which may be more than you want), as well as an info logging statement that reports the size of the corpus after every batch of texts. Here's an example of what I mean:

```
>>> import textacy
>>> import textacy.datasets
>>> ds = textacy.datasets.CapitolWords()
>>> texts = ds.texts(limit=200)
>>> corpus = textacy.Corpus('en')
>>> corpus.add_texts(texts, batch_size=50)  # note: default batch size is 1000
>>> print(corpus)
INFO:textacy.corpus:adding texts to Corpus(1 docs; 159 tokens)...
INFO:textacy.corpus:adding texts to Corpus(51 docs; 34125 tokens)...
INFO:textacy.corpus:adding texts to Corpus(101 docs; 71611 tokens)...
INFO:textacy.corpus:adding texts to Corpus(151 docs; 90684 tokens)...
Corpus(200 docs; 119000 tokens)
```

These changes will be in the next release of `textacy`.

There's also, generally, the problem that a `Corpus` requires all its data in-memory; at some point, your machine will run out of RAM. You can avoid this by skipping the `Corpus` and just iterating over a stream of texts => docs => whatever analysis you need, but it would be nice to have a fully streaming `Corpus` implementation. This has been in my backlog for a long time; I'll get to this, eventually.

**Comment by bdewilde** [comment] 2018-04-25 04:04
Hi again,

I've just added experimental support for reading and writing spacy docs to disk in binary format: https://github.com/chartbeat-labs/textacy/commit/12fbf10e8ac5758330b68477c72d57212e304249

The big advantage is that the data streams to/from disk one doc at a time, rather than reading everything into memory at once as a list when un/pickling. Could you let me know if this solves your other problem?

**Comment by brtknr** [comment] 2018-05-15 07:59
I am still trying to find an opportunity to test this but thanks in advance for your effort trying to resolve this :) it is much appreciated.

**Closed** 2019-05-18 17:57 UTC
